title: Aleksa Sormaz
logo: "/images/aleksa.jpg?raw=true"
description: >
  <b>Welcome</b> to my portfolio website!👋
  <br>
  Read more about me and feel free to reach out via social media!
  <br><br>
  <a href="https://www.linkedin.com/in/aleksasormaz/"><i class="fa fa-linkedin"></i> Visit My LinkedIn Profile</a>
  <br>
  <a href="https://github.com/SormazAleksa"><i class="fa fa-github-square"></i> Visit My GitHub Profile</a>
  <br>
  <a href="https://www.instagram.com/aleksa_sormaz/"><i class="fa fa-instagram"></i> Visit My Instagram Profile</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
